---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-metal-stack-io-v2-firewall
  failurePolicy: Fail
  name: firewall.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-metal-stack-io-v2-firewallset
  failurePolicy: Fail
  name: firewallset.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewallsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-metal-stack-io-v2-firewalldeployment
  failurePolicy: Fail
  name: firewalldeployment.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalldeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-metal-stack-io-v2-firewall
  failurePolicy: Fail
  name: firewall.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-metal-stack-io-v2-firewallset
  failurePolicy: Fail
  name: firewallset.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewallsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-metal-stack-io-v2-firewalldeployment
  failurePolicy: Fail
  name: firewalldeployment.metal-stack.io
  rules:
  - apiGroups:
    - metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalldeployments
  sideEffects: None
