---
apiVersion: firewall.metal-stack.io/v2
kind: FirewallDeployment
metadata:
  name: firewall
  namespace: firewall
spec:
  strategy: RollingUpdate
  replicas: 1
  selector:
    purpose: shoot-firewall
  template:
    metadata:
      labels:
        purpose: shoot-firewall
    spec:
      controllerURL: https://images.metal-stack.io/firewall-controller/latest/firewall-controller
      controllerVersion: latest
      size: v1-small-x86
      image: firewall-ubuntu-2.0
      partition: mini-lab
      project: 00000000-0000-0000-0000-000000000001
      networks:
        - internet-mini-lab
        - 7367e552-2126-4fee-a072-8a7b1c6173f8
      sshPublicKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPRflZEELGDvo49dZ0v9fWjMuXx2hADzT3fsUzuGJmzo6WDI8/MvG2ZPL02i8OuI1HbB200iIReCV7wsjVJ2gobonRxxYh6Ro+3GReBL3ZbtYwBsRSUZkp2sOqOfy3iOQZfmQL0mHETTMnwvwq0PdFPAu6PHo2d4yO0HX6sNdJD2G2dK6VXMKz3CmI1FRzVQx1856fu+z4qpqdEiBrXbYMs8sfCuCBL7/JccwStlhS6vChiF0rodLOxLMTwxdC/Eift5/kfMlt7LtZ+UbZ9ZBhoG4WvPjqI6E9qwEUcCfRAd8/XoLPyqs4I1VR3ZI2zd15eymxalA+6gT4kHaLDNakb8p0fKyecOOUTukIxWpw9YJ4YvlP7MdF9xVOpwD6cqpDiSq076qfkBONFl7g0S3v+t085wuuU9U0ETkwtnn40cRbkjal859PRqwsxakFgIUIB1zIgCvVes08yc3vVaCTn/Nj41d9qrwlUU3/ZSK+7gHK9hCERe+6IyXJ9d0H2+kWc2nARReVYUKLQILoI4vm64T8gvW3UhckxhAKIYBMTYGtwDzqWRuLZ/jt3xz96mUbq4xGHnF8BijrBJ+/8fV2Fz59okEw5f/6XzRr1vjOE826qSwaTdMpMQonlZoaAG8bh1eeD0OgacH2DUtpyXdUz18lLg+c0hcp7zr1O8c1Ew== mini-lab
