---
apiVersion: metal-stack.io/v2
kind: FirewallDeployment
metadata:
  name: firewall
  namespace: default
spec:
  strategy: Recreate
  replicas: 1
  template:
    size: v1-small-x86
    image: firewall-ubuntu-2.0
    partitionID: partition-a
    projectID: project-a
    networks:
      - internet
      - private-network
    sshpublickeys:
      - abcdef
